[package]
name = "datasplitter"
version = "0.1.0"
authors = ["dskleingeld <dskleingeldgmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
async-std = { version = "1.4.0", features = ["attributes"] }
warp = { version ="0.2", features=["tls"] }
reqwest = { version = "0.10", features = ["rustls-tls"] }